/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Index: typeof import('./src/components/Index.vue')['default']
    Login: typeof import('./src/components/sign/Login.vue')['default']
    MagicLink: typeof import('./src/components/sign/MagicLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/components/sign/SignUp.vue')['default']
    Storage: typeof import('./src/components/supe/Storage.vue')['default']
    SupeIndex: typeof import('./src/components/supe/SupeIndex.vue')['default']
  }
}
